### ISSUE TITLE
Automatic renewal

### ISSUE THREAD

**Issue by HLFH** [aeris/acme-pki#1]
Hi @aeris,

For the default client, [automatic renewal is supported with systemd](https://wiki.archlinux.org/index.php/Let%E2%80%99s_Encrypt#Automatic_renewal). Could we have the same feature with `acme-pki`?

Thanks,

**Comment by aeris** [comment]
This is more difficult to do with `acme-pki`, because you have to remember the CSR used to generate a CRT. By default, CSR is guessed from CRT name, but can be override by user.

Even if possible, I don’t see any justification to do it with systemd…
Better and simpler to use a simple cron script running each month, as mentioned on the [readme](https://github.com/aeris/acme-pki#user-content-renew-certificate).

**Comment by HLFH** [comment]
Ok. I guess it will be a `won't fix`. I'm using `systemd` and its timers, so I chose not to use cron.
